### ISSUE TITLE
Default overriding of "default_filters" is not mentioned in documentation.

### ISSUE THREAD

**Issue by cpburnz** [Pylons/pyramid_mako#42]
Mako has a default for [default_filters](https://docs.makotemplates.org/en/latest/filtering.html#the-default-filters-argument) depending on a couple settings. It appears that *pyramid_mako* [overrides](https://github.com/Pylons/pyramid_mako/blob/917254f8ba01574b539652c30f8e695a7aeb254f/pyramid_mako/__init__.py#L189) Mako's *default_filters* setting to `['h']` (HTML escaping) when *mako.default_filters* is not explicitly set. This behavior does not appear to be documented in *pyramid_mako*'s [documentation](https://docs.pylonsproject.org/projects/pyramid-mako/en/latest/). I'm not objecting to this safe default but it was unexpected and documenting it would be beneficial.

**Comment by stevepiercy** [comment]
I think that sounds reasonable. Would you be willing to submit a pull request? I'd suggest editing the section on [Mako Default Filters](https://docs.pylonsproject.org/projects/pyramid-mako/en/latest/#mako-default-filters).
