### ISSUE TITLE
Support for python 3.9+ versions?

### ISSUE THREAD

**Issue by dylannorthrup** [Pylons/pyramid_mako#66]
I see in the [changelog](https://github.com/Pylons/pyramid_mako/blob/main/CHANGES.txt) there are unreleased updates to support python versions up to 3.11. I'm trying to deploy on 3.9.x and am running into issues (`pyramid` is not properly importing `pyramid_mako` so there are no renderers available for '*.mak' files). I'm hoping those are version-related and will be fixed with 3.11 support.

I'm opening this issue to see if there's an ETA for the newer version support as well as a way to notify me when that support is added and this issue is closed.

Thanks in advance!

**Comment by digitalresistor** [comment]
How are you importing `pyramid_mako` into your Pyramid project? AFAIK there are no relevant changes that would suddenly make it work.

```
config = Configurator()
config.include('pyramid_mako')
```

Should continue to function as-is.

**Comment by dylannorthrup** [comment]
I cannot find which repository I was encountering these issues in, and cannot reproduce whatever issue i was encountering. I'll close this issue and, should I encounter the issue again, re-open with additional context for reproduction (and for me to re-find the repository I encountered the issue in).

My apologies.
